name: Build

on:
  push:
    paths:
      - 'sane-epkowa/**'
      - '.github/**'

jobs:
  build:
    strategy:
      matrix:
        include:
          - sdk: ramips-mt76x8
            target: mipsel_24kc
    runs-on: ubuntu-latest
    container: 
      image: openwrtorg/sdk:${{ matrix.sdk }}-21.02.0
      options: --user root
    defaults:
      run:
        working-directory: /home/build/openwrt
    steps:
      - name: Add feeds
        run: echo "src-git epkowa https://github.com/ypopovych/sane-epkowa-openwrt.git^${GITHUB_SHA}" >> feeds.conf.default
      - name: Update feeds
        run: ./scripts/feeds update base packages epkowa
      - name: Make defconfig
        run: make defconfig
      - name: Install feeds
        run: ./scripts/feeds install sane-epkowa
      - name: Compile
        run: make package/sane-epkowa/compile -j$(nproc)
      - name: Get version
        run: |
          export MAKEFILE="./feeds/epkowa/sane-epkowa/Makefile"
          export PKG_SOURCE_DATE=`sed -n "s/^PKG_SOURCE_DATE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_SOURCE_VERSION=`sed -n "s/^PKG_SOURCE_VERSION:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_RELEASE=`sed -n "s/^PKG_RELEASE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_VERSION="$PKG_SOURCE_DATE-$PKG_SOURCE_VERSION"
          echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV
          echo "PKG_FULL_VERSION=$PKG_VERSION-$PKG_RELEASE" >> $GITHUB_ENV
      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: sane-epkowa_${{ env.PKG_FULL_VERSION }}_${{ matrix.target }}.ipk
          path: /home/build/openwrt/bin/packages/${{ matrix.target }}/sane-epkowa/sane-epkowa_${{ env.PKG_FULL_VERSION }}_${{ matrix.target }}.ipk
